---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: qbittorrent-secret-push
  namespace: download
spec:
  refreshInterval: 1h
  deletionPolicy: None
  secretStoreRefs:
    - name: openbao
      kind: ClusterSecretStore
  selector:
    secret:
      name: qbittorrent-secret
  data:
    - match:
        secretKey: VPN_SERVICE_PROVIDER
        remoteRef:
          remoteKey: download/qbittorrent-secret
    - match:
        secretKey: VPN_TYPE
        remoteRef:
          remoteKey: download/qbittorrent-secret
    - match:
        secretKey: WIREGUARD_PRIVATE_KEY
        remoteRef:
          remoteKey: download/qbittorrent-secret
    - match:
        secretKey: WIREGUARD_ADDRESSES
        remoteRef:
          remoteKey: download/qbittorrent-secret
    - match:
        secretKey: SERVER_COUNTRIES
        remoteRef:
          remoteKey: download/qbittorrent-secret
