---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name unifi-phantom-clients-cleanup-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        UNIFI_HOST: "{{ .UnifiPhantomClients__Host }}"
        UNIFI_SITE: "{{ .UnifiPhantomClients__Site }}"
        UNIFI_USERNAME: "{{ .UnifiPhantomClients__Username }}"
        UNIFI_PASSWORD: "{{ .UnifiPhantomClients__Password }}"
        UNIFI_UDMP: "{{ .UnifiPhantomClients__Udmp }}"
        UNIFI_VALIDATE_CERTIFICATE: "{{ .UnifiPhantomClients__ValidateCertificate }}"
  dataFrom:
    - extract:
        key: unifi-phantom-clients
