---
apiVersion: v1
kind: Service
metadata:
  name: dev-shell
  labels:
    app.kubernetes.io/name: dev-shell
    app.kubernetes.io/instance: dev-shell
spec:
  type: ClusterIP
  ports:
    - port: 2222
      targetPort: ssh
      protocol: TCP
      name: ssh
  selector:
    app.kubernetes.io/name: dev-shell
    app.kubernetes.io/instance: dev-shell
