---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: couchdb-secret-push
  namespace: database
spec:
  refreshInterval: 1h
  deletionPolicy: None
  secretStoreRefs:
    - name: openbao
      kind: ClusterSecretStore
  selector:
    secret:
      name: couchdb-secret
  data:
    - match:
        secretKey: COUCHDB_USER
        remoteRef:
          remoteKey: database/couchdb-secret
    - match:
        secretKey: COUCHDB_PASSWORD
        remoteRef:
          remoteKey: database/couchdb-secret
    - match:
        secretKey: 20-secrets.ini
        remoteRef:
          remoteKey: database/couchdb-secret
