---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: frigate-secret-push
  namespace: home
spec:
  refreshInterval: 1h
  deletionPolicy: None
  secretStoreRefs:
    - name: openbao
      kind: ClusterSecretStore
  selector:
    secret:
      name: frigate-secret
  data:
    - match:
        secretKey: FRIGATE_POSTGRES_HOST
        remoteRef:
          remoteKey: home/frigate-secret
    - match:
        secretKey: FRIGATE_POSTGRES_PORT
        remoteRef:
          remoteKey: home/frigate-secret
    - match:
        secretKey: FRIGATE_POSTGRES_USER
        remoteRef:
          remoteKey: home/frigate-secret
    - match:
        secretKey: FRIGATE_POSTGRES_PASSWORD
        remoteRef:
          remoteKey: home/frigate-secret
    - match:
        secretKey: FRIGATE_POSTGRES_DB
        remoteRef:
          remoteKey: home/frigate-secret
    - match:
        secretKey: INIT_POSTGRES_HOST
        remoteRef:
          remoteKey: home/frigate-secret
    - match:
        secretKey: INIT_POSTGRES_USER
        remoteRef:
          remoteKey: home/frigate-secret
    - match:
        secretKey: INIT_POSTGRES_PASS
        remoteRef:
          remoteKey: home/frigate-secret
    - match:
        secretKey: INIT_POSTGRES_DBNAME
        remoteRef:
          remoteKey: home/frigate-secret
    - match:
        secretKey: INIT_POSTGRES_SUPER_PASS
        remoteRef:
          remoteKey: home/frigate-secret
    - match:
        secretKey: FRIGATE_MQTT_USER
        remoteRef:
          remoteKey: home/frigate-secret
    - match:
        secretKey: FRIGATE_MQTT_PASSWORD
        remoteRef:
          remoteKey: home/frigate-secret
    - match:
        secretKey: FRIGATE_RTSP_USER
        remoteRef:
          remoteKey: home/frigate-secret
    - match:
        secretKey: FRIGATE_RTSP_PASSWORD
        remoteRef:
          remoteKey: home/frigate-secret
