---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: karakeep-secret-push
  namespace: productivity
spec:
  refreshInterval: 1h
  deletionPolicy: None
  secretStoreRefs:
    - name: openbao
      kind: ClusterSecretStore
  selector:
    secret:
      name: karakeep-secret
  data:
    - match:
        secretKey: NEXTAUTH_SECRET
        remoteRef:
          remoteKey: productivity/karakeep-secret
    - match:
        secretKey: MEILI_MASTER_KEY
        remoteRef:
          remoteKey: productivity/karakeep-secret
    - match:
        secretKey: INIT_POSTGRES_DBNAME
        remoteRef:
          remoteKey: productivity/karakeep-secret
    - match:
        secretKey: INIT_POSTGRES_HOST
        remoteRef:
          remoteKey: productivity/karakeep-secret
    - match:
        secretKey: INIT_POSTGRES_USER
        remoteRef:
          remoteKey: productivity/karakeep-secret
    - match:
        secretKey: INIT_POSTGRES_PASS
        remoteRef:
          remoteKey: productivity/karakeep-secret
    - match:
        secretKey: INIT_POSTGRES_SUPER_PASS
        remoteRef:
          remoteKey: productivity/karakeep-secret
    - match:
        secretKey: DATABASE_URL
        remoteRef:
          remoteKey: productivity/karakeep-secret
    - match:
        secretKey: OAUTH_CLIENT_ID
        remoteRef:
          remoteKey: productivity/karakeep-secret
    - match:
        secretKey: OAUTH_CLIENT_SECRET
        remoteRef:
          remoteKey: productivity/karakeep-secret
    - match:
        secretKey: OPENAI_API_KEY
        remoteRef:
          remoteKey: productivity/karakeep-secret
    - match:
        secretKey: OPENAI_BASE_URL
        remoteRef:
          remoteKey: productivity/karakeep-secret
