---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: alertmanager-secret-push
  namespace: observability
spec:
  refreshInterval: 1h
  deletionPolicy: None
  secretStoreRefs:
    - name: openbao
      kind: ClusterSecretStore
  selector:
    secret:
      name: alertmanager-secret
  data:
    - match:
        secretKey: ALERTMANAGER_HEARTBEAT_URL
        remoteRef:
          remoteKey: observability/alertmanager-secret
    - match:
        secretKey: ALERTMANAGER_PUSHOVER_TOKEN
        remoteRef:
          remoteKey: observability/alertmanager-secret
    - match:
        secretKey: PUSHOVER_USER_KEY
        remoteRef:
          remoteKey: observability/alertmanager-secret
