---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: nexus-secret-push
  namespace: develop
spec:
  refreshInterval: 1h
  deletionPolicy: None
  secretStoreRefs:
    - name: openbao
      kind: ClusterSecretStore
  selector:
    secret:
      name: nexus-secret
  data:
    - match:
        secretKey: INIT_POSTGRES_HOST
        remoteRef:
          remoteKey: develop/nexus-secret
    - match:
        secretKey: INIT_POSTGRES_USER
        remoteRef:
          remoteKey: develop/nexus-secret
    - match:
        secretKey: INIT_POSTGRES_PASS
        remoteRef:
          remoteKey: develop/nexus-secret
    - match:
        secretKey: INIT_POSTGRES_DBNAME
        remoteRef:
          remoteKey: develop/nexus-secret
    - match:
        secretKey: INIT_POSTGRES_SUPER_PASS
        remoteRef:
          remoteKey: develop/nexus-secret
    - match:
        secretKey: NEXUS_SECURITY_RANDOMPASSWORD
        remoteRef:
          remoteKey: develop/nexus-secret
    - match:
        secretKey: NEXUS_SECURITY_INITIAL_PASSWORD
        remoteRef:
          remoteKey: develop/nexus-secret
    - match:
        secretKey: NEXUS_ADMIN_USERNAME
        remoteRef:
          remoteKey: develop/nexus-secret
    - match:
        secretKey: NEXUS_DATASTORE_NEXUS_JDBCURL
        remoteRef:
          remoteKey: develop/nexus-secret
    - match:
        secretKey: NEXUS_DATASTORE_NEXUS_USERNAME
        remoteRef:
          remoteKey: develop/nexus-secret
    - match:
        secretKey: NEXUS_DATASTORE_NEXUS_PASSWORD
        remoteRef:
          remoteKey: develop/nexus-secret
