---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./vlan-10.yaml
  - ./vlan-30.yaml
  - ./vlan-50.yaml

