---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - serviceaccount.yaml
  - externalsecret.yaml
  - configmap.yaml
  - deployment.yaml
  - podmonitor.yaml
  - prometheusrule.yaml
