---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: authentik-push
  namespace: identity
spec:
  refreshInterval: 1h
  deletionPolicy: None
  secretStoreRefs:
    - name: openbao
      kind: ClusterSecretStore
  selector:
    secret:
      name: authentik
  data:
    - match:
        secretKey: INIT_POSTGRES_SUPER_PASS
        remoteRef:
          remoteKey: identity/authentik
    - match:
        secretKey: INIT_POSTGRES_DBNAME
        remoteRef:
          remoteKey: identity/authentik
    - match:
        secretKey: INIT_POSTGRES_HOST
        remoteRef:
          remoteKey: identity/authentik
    - match:
        secretKey: INIT_POSTGRES_USER
        remoteRef:
          remoteKey: identity/authentik
    - match:
        secretKey: INIT_POSTGRES_PASS
        remoteRef:
          remoteKey: identity/authentik
    - match:
        secretKey: AUTHENTIK_SECRET_KEY
        remoteRef:
          remoteKey: identity/authentik
    - match:
        secretKey: AUTHENTIK_BOOTSTRAP_PASSWORD
        remoteRef:
          remoteKey: identity/authentik
    - match:
        secretKey: AUTHENTIK_BOOTSTRAP_TOKEN
        remoteRef:
          remoteKey: identity/authentik
    - match:
        secretKey: AUTHENTIK_BOOTSTRAP_EMAIL
        remoteRef:
          remoteKey: identity/authentik
    - match:
        secretKey: AUTHENTIK_POSTGRESQL__HOST
        remoteRef:
          remoteKey: identity/authentik
    - match:
        secretKey: AUTHENTIK_POSTGRESQL__NAME
        remoteRef:
          remoteKey: identity/authentik
    - match:
        secretKey: AUTHENTIK_POSTGRESQL__USER
        remoteRef:
          remoteKey: identity/authentik
    - match:
        secretKey: AUTHENTIK_POSTGRESQL__PASSWORD
        remoteRef:
          remoteKey: identity/authentik
    - match:
        secretKey: AUTHENTIK_REDIS__HOST
        remoteRef:
          remoteKey: identity/authentik
