---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: kometa-secret-push
  namespace: media
spec:
  refreshInterval: 1h
  deletionPolicy: None
  secretStoreRefs:
    - name: openbao
      kind: ClusterSecretStore
  selector:
    secret:
      name: kometa-secret
  data:
    - match:
        secretKey: KOMETA_MDBLIST_API_KEY
        remoteRef:
          remoteKey: media/kometa-secret
    - match:
        secretKey: KOMETA_OMDB_API_KEY
        remoteRef:
          remoteKey: media/kometa-secret
    - match:
        secretKey: KOMETA_TMDB_API_KEY
        remoteRef:
          remoteKey: media/kometa-secret
    - match:
        secretKey: KOMETA_MYANIMELIST_CLIENT_ID
        remoteRef:
          remoteKey: media/kometa-secret
    - match:
        secretKey: KOMETA_MYANIMELIST_CLIENT_SECRET
        remoteRef:
          remoteKey: media/kometa-secret
    - match:
        secretKey: KOMETA_MYANIMELIST_ACCESS_TOKEN
        remoteRef:
          remoteKey: media/kometa-secret
    - match:
        secretKey: KOMETA_MYANIMELIST_REFRESH_TOKEN
        remoteRef:
          remoteKey: media/kometa-secret
    - match:
        secretKey: KOMETA_MYANIMELIST_EXPIRES_IN
        remoteRef:
          remoteKey: media/kometa-secret
    - match:
        secretKey: KOMETA_MYANIMELIST_LOCALHOST_URL
        remoteRef:
          remoteKey: media/kometa-secret
    - match:
        secretKey: KOMETA_TRAKT_CLIENT_ID
        remoteRef:
          remoteKey: media/kometa-secret
    - match:
        secretKey: KOMETA_TRAKT_CLIENT_SECRET
        remoteRef:
          remoteKey: media/kometa-secret
    - match:
        secretKey: KOMETA_TRAKT_ACCESS_TOKEN
        remoteRef:
          remoteKey: media/kometa-secret
    - match:
        secretKey: KOMETA_TRAKT_REFRESH_TOKEN
        remoteRef:
          remoteKey: media/kometa-secret
    - match:
        secretKey: KOMETA_TRAKT_EXPIRES_IN
        remoteRef:
          remoteKey: media/kometa-secret
    - match:
        secretKey: KOMETA_TRAKT_CREATED_AT
        remoteRef:
          remoteKey: media/kometa-secret
    - match:
        secretKey: KOMETA_PLEX_API_KEY
        remoteRef:
          remoteKey: media/kometa-secret
    - match:
        secretKey: KOMETA_TAUTULLI_API_KEY
        remoteRef:
          remoteKey: media/kometa-secret
    - match:
        secretKey: KOMETA_RADARR_API_KEY
        remoteRef:
          remoteKey: media/kometa-secret
    - match:
        secretKey: KOMETA_SONARR_API_KEY
        remoteRef:
          remoteKey: media/kometa-secret
