---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: homepage-secret-push
  namespace: home
spec:
  refreshInterval: 1h
  deletionPolicy: None
  secretStoreRefs:
    - name: openbao
      kind: ClusterSecretStore
  selector:
    secret:
      name: homepage-secret
  data:
    - match:
        secretKey: HOMEPAGE_VAR_CLOUDFLARED_ACCOUNTID
        remoteRef:
          remoteKey: home/homepage-secret
    - match:
        secretKey: HOMEPAGE_VAR_CLOUDFLARED_TUNNELID
        remoteRef:
          remoteKey: home/homepage-secret
    - match:
        secretKey: HOMEPAGE_VAR_CLOUDFLARED_API_TOKEN
        remoteRef:
          remoteKey: home/homepage-secret
    - match:
        secretKey: HOMEPAGE_VAR_UNIFI_USERNAME
        remoteRef:
          remoteKey: home/homepage-secret
    - match:
        secretKey: HOMEPAGE_VAR_UNIFI_PASSWORD
        remoteRef:
          remoteKey: home/homepage-secret
    - match:
        secretKey: HOMEPAGE_VAR_TRUENAS_APIKEY
        remoteRef:
          remoteKey: home/homepage-secret
    - match:
        secretKey: HOMEPAGE_VAR_TRUENAS_HOST
        remoteRef:
          remoteKey: home/homepage-secret
    - match:
        secretKey: HOMEPAGE_VAR_HASS_TOKEN
        remoteRef:
          remoteKey: home/homepage-secret
    - match:
        secretKey: HOMEPAGE_VAR_AUTOBRR_TOKEN
        remoteRef:
          remoteKey: home/homepage-secret
    - match:
        secretKey: HOMEPAGE_VAR_QBITTORRENT_USERNAME
        remoteRef:
          remoteKey: home/homepage-secret
    - match:
        secretKey: HOMEPAGE_VAR_QBITTORRENT_PASSWORD
        remoteRef:
          remoteKey: home/homepage-secret
    - match:
        secretKey: HOMEPAGE_VAR_SABNZBD_TOKEN
        remoteRef:
          remoteKey: home/homepage-secret
    - match:
        secretKey: HOMEPAGE_VAR_BAZARR_TOKEN
        remoteRef:
          remoteKey: home/homepage-secret
    - match:
        secretKey: HOMEPAGE_VAR_LIDARR_TOKEN
        remoteRef:
          remoteKey: home/homepage-secret
    - match:
        secretKey: HOMEPAGE_VAR_PROWLARR_TOKEN
        remoteRef:
          remoteKey: home/homepage-secret
    - match:
        secretKey: HOMEPAGE_VAR_RADARR_TOKEN
        remoteRef:
          remoteKey: home/homepage-secret
    - match:
        secretKey: HOMEPAGE_VAR_READARR_AUDIOBOOKS_TOKEN
        remoteRef:
          remoteKey: home/homepage-secret
    - match:
        secretKey: HOMEPAGE_VAR_READARR_EBOOKS_TOKEN
        remoteRef:
          remoteKey: home/homepage-secret
    - match:
        secretKey: HOMEPAGE_VAR_SONARR_TOKEN
        remoteRef:
          remoteKey: home/homepage-secret
    - match:
        secretKey: HOMEPAGE_VAR_AUDIOBOOKSHELF_TOKEN
        remoteRef:
          remoteKey: home/homepage-secret
    - match:
        secretKey: HOMEPAGE_VAR_CALIBRE_USERNAME
        remoteRef:
          remoteKey: home/homepage-secret
    - match:
        secretKey: HOMEPAGE_VAR_CALIBRE_PASSWORD
        remoteRef:
          remoteKey: home/homepage-secret
    - match:
        secretKey: HOMEPAGE_VAR_IMMICH_TOKEN
        remoteRef:
          remoteKey: home/homepage-secret
    - match:
        secretKey: HOMEPAGE_VAR_JELLYFIN_TOKEN
        remoteRef:
          remoteKey: home/homepage-secret
    - match:
        secretKey: HOMEPAGE_VAR_JELLYSEERR_TOKEN
        remoteRef:
          remoteKey: home/homepage-secret
    - match:
        secretKey: HOMEPAGE_VAR_PLEX_TOKEN
        remoteRef:
          remoteKey: home/homepage-secret
    - match:
        secretKey: HOMEPAGE_VAR_TAUTULLI_TOKEN
        remoteRef:
          remoteKey: home/homepage-secret
    - match:
        secretKey: HOMEPAGE_VAR_GROCY_TOKEN
        remoteRef:
          remoteKey: home/homepage-secret
    - match:
        secretKey: HOMEPAGE_VAR_MEALIE_TOKEN
        remoteRef:
          remoteKey: home/homepage-secret
    - match:
        secretKey: HOMEPAGE_VAR_NEXTCLOUD_USERNAME
        remoteRef:
          remoteKey: home/homepage-secret
    - match:
        secretKey: HOMEPAGE_VAR_NEXTCLOUD_PASSWORD
        remoteRef:
          remoteKey: home/homepage-secret
    - match:
        secretKey: HOMEPAGE_VAR_AUTHENTIK_TOKEN
        remoteRef:
          remoteKey: home/homepage-secret
    - match:
        secretKey: HOMEPAGE_VAR_GRAFANA_USERNAME
        remoteRef:
          remoteKey: home/homepage-secret
    - match:
        secretKey: HOMEPAGE_VAR_GRAFANA_PASSWORD
        remoteRef:
          remoteKey: home/homepage-secret
    - match:
        secretKey: HOMEPAGE_VAR_LATITUDE
        remoteRef:
          remoteKey: home/homepage-secret
    - match:
        secretKey: HOMEPAGE_VAR_LONGITUDE
        remoteRef:
          remoteKey: home/homepage-secret
