apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: ts-exit-node
spec:
  hostname: ts-exit-node
  exitNode: true
  subnetRouter:
    advertiseRoutes:
      - "10.0.10.0/24"
      - "10.25.52.0/22"
      - "10.0.30.0/24"
      - "10.0.50.0/24"
      - "172.16.8.0/24"
