---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: n8n-secret-push
  namespace: productivity
spec:
  refreshInterval: 1h
  deletionPolicy: None
  secretStoreRefs:
    - name: openbao
      kind: ClusterSecretStore
  selector:
    secret:
      name: n8n-secret
  data:
    - match:
        secretKey: DB_POSTGRESDB_HOST
        remoteRef:
          remoteKey: productivity/n8n-secret
    - match:
        secretKey: DB_POSTGRESDB_PORT
        remoteRef:
          remoteKey: productivity/n8n-secret
    - match:
        secretKey: DB_POSTGRESDB_DATABASE
        remoteRef:
          remoteKey: productivity/n8n-secret
    - match:
        secretKey: DB_POSTGRESDB_USER
        remoteRef:
          remoteKey: productivity/n8n-secret
    - match:
        secretKey: DB_POSTGRESDB_PASSWORD
        remoteRef:
          remoteKey: productivity/n8n-secret
    - match:
        secretKey: N8N_ENCRYPTION_KEY
        remoteRef:
          remoteKey: productivity/n8n-secret
    - match:
        secretKey: INIT_POSTGRES_DBNAME
        remoteRef:
          remoteKey: productivity/n8n-secret
    - match:
        secretKey: INIT_POSTGRES_HOST
        remoteRef:
          remoteKey: productivity/n8n-secret
    - match:
        secretKey: INIT_POSTGRES_USER
        remoteRef:
          remoteKey: productivity/n8n-secret
    - match:
        secretKey: INIT_POSTGRES_PASS
        remoteRef:
          remoteKey: productivity/n8n-secret
    - match:
        secretKey: INIT_POSTGRES_SUPER_PASS
        remoteRef:
          remoteKey: productivity/n8n-secret
    - match:
        secretKey: OPENAI_API_KEY
        remoteRef:
          remoteKey: productivity/n8n-secret
    - match:
        secretKey: OPENAI_BASE_URL
        remoteRef:
          remoteKey: productivity/n8n-secret
