---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: autobrr-secret-push
  namespace: download
spec:
  refreshInterval: 1h
  deletionPolicy: None
  secretStoreRefs:
    - name: openbao
      kind: ClusterSecretStore
  selector:
    secret:
      name: autobrr-secret
  data:
    - match:
        secretKey: AUTOBRR__SESSION_SECRET
        remoteRef:
          remoteKey: download/autobrr-secret
    - match:
        secretKey: AUTOBRR__DATABASE_TYPE
        remoteRef:
          remoteKey: download/autobrr-secret
    - match:
        secretKey: AUTOBRR__POSTGRES_HOST
        remoteRef:
          remoteKey: download/autobrr-secret
    - match:
        secretKey: AUTOBRR__POSTGRES_PORT
        remoteRef:
          remoteKey: download/autobrr-secret
    - match:
        secretKey: AUTOBRR__POSTGRES_USER
        remoteRef:
          remoteKey: download/autobrr-secret
    - match:
        secretKey: AUTOBRR__POSTGRES_PASS
        remoteRef:
          remoteKey: download/autobrr-secret
    - match:
        secretKey: AUTOBRR__POSTGRES_DATABASE
        remoteRef:
          remoteKey: download/autobrr-secret
    - match:
        secretKey: INIT_POSTGRES_HOST
        remoteRef:
          remoteKey: download/autobrr-secret
    - match:
        secretKey: INIT_POSTGRES_USER
        remoteRef:
          remoteKey: download/autobrr-secret
    - match:
        secretKey: INIT_POSTGRES_PASS
        remoteRef:
          remoteKey: download/autobrr-secret
    - match:
        secretKey: INIT_POSTGRES_DBNAME
        remoteRef:
          remoteKey: download/autobrr-secret
    - match:
        secretKey: INIT_POSTGRES_SUPER_PASS
        remoteRef:
          remoteKey: download/autobrr-secret
