---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: external-dns-secret-cloudflare-push
  namespace: network
spec:
  refreshInterval: 1h
  deletionPolicy: None
  secretStoreRefs:
    - name: openbao
      kind: ClusterSecretStore
  selector:
    secret:
      name: external-dns-secret-cloudflare
  data:
    - match:
        secretKey: api-token
        remoteRef:
          remoteKey: network/external-dns-secret-cloudflare
