---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name gitea-registry-creds
spec:
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: *name
    template:
      engineVersion: v2
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "gitea.derekjacobs.dev": {
                "username": "{{ .GiteaRegistry__Username }}",
                "password": "{{ .GiteaRegistry__Token }}",
                "auth": "{{ (printf "%s:%s" .GiteaRegistry__Username .GiteaRegistry__Token) | b64enc }}"
              }
            }
          }
  dataFrom:
    - extract:
        key: gitea-registry
