# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app bluevulpine-blog
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: bluevulpine-blog
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      bluevulpine-blog:
        type: deployment
        replicas: 1
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: gitea.derekjacobs.dev/bluevulpine/bluevulpine.net.web
              tag: "8-d23bc0b1" # {"$imagepolicy": "flux-system:bluevulpine-blog:tag"}
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 8080
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 10m
                memory: 16Mi
              limits:
                memory: 128Mi
        pod:
          imagePullSecrets:
            - name: gitea-registry-creds
          securityContext:
            runAsUser: 101
            runAsGroup: 101
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
    service:
      app:
        controller: bluevulpine-blog
        ports:
          http:
            port: *port
    persistence:
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
      cache:
        type: emptyDir
        globalMounts:
          - path: /var/cache/nginx
