---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: grafana-secret-push
  namespace: observability
spec:
  refreshInterval: 1h
  deletionPolicy: None
  secretStoreRefs:
    - name: openbao
      kind: ClusterSecretStore
  selector:
    secret:
      name: grafana-secret
  data:
    - match:
        secretKey: GF_DATABASE_NAME
        remoteRef:
          remoteKey: observability/grafana-secret
    - match:
        secretKey: GF_DATABASE_HOST
        remoteRef:
          remoteKey: observability/grafana-secret
    - match:
        secretKey: GF_DATABASE_USER
        remoteRef:
          remoteKey: observability/grafana-secret
    - match:
        secretKey: GF_DATABASE_PASSWORD
        remoteRef:
          remoteKey: observability/grafana-secret
    - match:
        secretKey: GF_DATABASE_SSL_MODE
        remoteRef:
          remoteKey: observability/grafana-secret
    - match:
        secretKey: GF_DATABASE_TYPE
        remoteRef:
          remoteKey: observability/grafana-secret
    - match:
        secretKey: GF_AUTH_GENERIC_OAUTH_CLIENT_ID
        remoteRef:
          remoteKey: observability/grafana-secret
    - match:
        secretKey: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
        remoteRef:
          remoteKey: observability/grafana-secret
    - match:
        secretKey: INIT_POSTGRES_DBNAME
        remoteRef:
          remoteKey: observability/grafana-secret
    - match:
        secretKey: INIT_POSTGRES_HOST
        remoteRef:
          remoteKey: observability/grafana-secret
    - match:
        secretKey: INIT_POSTGRES_USER
        remoteRef:
          remoteKey: observability/grafana-secret
    - match:
        secretKey: INIT_POSTGRES_PASS
        remoteRef:
          remoteKey: observability/grafana-secret
    - match:
        secretKey: INIT_POSTGRES_SUPER_PASS
        remoteRef:
          remoteKey: observability/grafana-secret
