---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/imagerepository-image-v1.json
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: &app kia-trip-archiver
spec:
  image: gitea.derekjacobs.dev/bluevulpine/kia-trip-archiver
  interval: 5m
  secretRef:
    name: gitea-registry-creds
