---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: rreading-glasses-secret-push
  namespace: media
spec:
  refreshInterval: 1h
  deletionPolicy: None
  secretStoreRefs:
    - name: openbao
      kind: ClusterSecretStore
  selector:
    secret:
      name: rreading-glasses-secret
  data:
    - match:
        secretKey: POSTGRES_HOST
        remoteRef:
          remoteKey: media/rreading-glasses-secret
    - match:
        secretKey: POSTGRES_DATABASE
        remoteRef:
          remoteKey: media/rreading-glasses-secret
    - match:
        secretKey: POSTGRES_USER
        remoteRef:
          remoteKey: media/rreading-glasses-secret
    - match:
        secretKey: POSTGRES_PASSWORD
        remoteRef:
          remoteKey: media/rreading-glasses-secret
    - match:
        secretKey: HARDCOVER_AUTH
        remoteRef:
          remoteKey: media/rreading-glasses-secret
    - match:
        secretKey: INIT_POSTGRES_HOST
        remoteRef:
          remoteKey: media/rreading-glasses-secret
    - match:
        secretKey: INIT_POSTGRES_USER
        remoteRef:
          remoteKey: media/rreading-glasses-secret
    - match:
        secretKey: INIT_POSTGRES_PASS
        remoteRef:
          remoteKey: media/rreading-glasses-secret
    - match:
        secretKey: INIT_POSTGRES_DBNAME
        remoteRef:
          remoteKey: media/rreading-glasses-secret
    - match:
        secretKey: INIT_POSTGRES_SUPER_PASS
        remoteRef:
          remoteKey: media/rreading-glasses-secret
