---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: immich-secret-push
  namespace: media
spec:
  refreshInterval: 1h
  deletionPolicy: None
  secretStoreRefs:
    - name: openbao
      kind: ClusterSecretStore
  selector:
    secret:
      name: immich-secret
  data:
    - match:
        secretKey: DB_HOSTNAME
        remoteRef:
          remoteKey: media/immich-secret
    - match:
        secretKey: DB_PORT
        remoteRef:
          remoteKey: media/immich-secret
    - match:
        secretKey: DB_USERNAME
        remoteRef:
          remoteKey: media/immich-secret
    - match:
        secretKey: DB_PASSWORD
        remoteRef:
          remoteKey: media/immich-secret
    - match:
        secretKey: DB_DATABASE_NAME
        remoteRef:
          remoteKey: media/immich-secret
    - match:
        secretKey: DB_URL
        remoteRef:
          remoteKey: media/immich-secret
    - match:
        secretKey: INIT_POSTGRES_HOST
        remoteRef:
          remoteKey: media/immich-secret
    - match:
        secretKey: INIT_POSTGRES_USER
        remoteRef:
          remoteKey: media/immich-secret
    - match:
        secretKey: INIT_POSTGRES_PASS
        remoteRef:
          remoteKey: media/immich-secret
    - match:
        secretKey: INIT_POSTGRES_DBNAME
        remoteRef:
          remoteKey: media/immich-secret
    - match:
        secretKey: INIT_POSTGRES_SUPER_PASS
        remoteRef:
          remoteKey: media/immich-secret
    - match:
        secretKey: REDIS_HOSTNAME
        remoteRef:
          remoteKey: media/immich-secret
    - match:
        secretKey: REDIS_PORT
        remoteRef:
          remoteKey: media/immich-secret
    - match:
        secretKey: IMMICH_SECRET_KEY
        remoteRef:
          remoteKey: media/immich-secret
