---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: gatus-secret-push
  namespace: observability
spec:
  refreshInterval: 1h
  deletionPolicy: None
  secretStoreRefs:
    - name: openbao
      kind: ClusterSecretStore
  selector:
    secret:
      name: gatus-secret
  data:
    - match:
        secretKey: INIT_POSTGRES_SUPER_PASS
        remoteRef:
          remoteKey: observability/gatus-secret
    - match:
        secretKey: INIT_POSTGRES_DBNAME
        remoteRef:
          remoteKey: observability/gatus-secret
    - match:
        secretKey: INIT_POSTGRES_HOST
        remoteRef:
          remoteKey: observability/gatus-secret
    - match:
        secretKey: INIT_POSTGRES_USER
        remoteRef:
          remoteKey: observability/gatus-secret
    - match:
        secretKey: INIT_POSTGRES_PASS
        remoteRef:
          remoteKey: observability/gatus-secret
    - match:
        secretKey: CUSTOM_PUSHOVER_TOKEN
        remoteRef:
          remoteKey: observability/gatus-secret
    - match:
        secretKey: CUSTOM_PUSHOVER_USER_KEY
        remoteRef:
          remoteKey: observability/gatus-secret
    - match:
        secretKey: GATUS_AUTHENTIK_BASIC_AUTH
        remoteRef:
          remoteKey: observability/gatus-secret
