---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: homebox-companion-secret-push
  namespace: productivity
spec:
  refreshInterval: 1h
  deletionPolicy: None
  secretStoreRefs:
    - name: openbao
      kind: ClusterSecretStore
  selector:
    secret:
      name: homebox-companion-secret
  data:
    - match:
        secretKey: HBC_LLM_API_KEY
        remoteRef:
          remoteKey: productivity/homebox-companion-secret
    - match:
        secretKey: HBC_LLM_API_BASE
        remoteRef:
          remoteKey: productivity/homebox-companion-secret
