---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: cloudflare-tunnel-secret-push
  namespace: network
spec:
  refreshInterval: 1h
  deletionPolicy: None
  secretStoreRefs:
    - name: openbao
      kind: ClusterSecretStore
  selector:
    secret:
      name: cloudflare-tunnel-secret
  data:
    - match:
        secretKey: TUNNEL_ID
        remoteRef:
          remoteKey: network/cloudflare-tunnel-secret
    - match:
        secretKey: credentials.json
        remoteRef:
          remoteKey: network/cloudflare-tunnel-secret
