---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: mosquitto-secret-push
  namespace: home
spec:
  refreshInterval: 1h
  deletionPolicy: None
  secretStoreRefs:
    - name: openbao
      kind: ClusterSecretStore
  selector:
    secret:
      name: mosquitto-secret
  data:
    - match:
        secretKey: acl.conf
        remoteRef:
          remoteKey: home/mosquitto-secret
    - match:
        secretKey: mosquitto.conf
        remoteRef:
          remoteKey: home/mosquitto-secret
    - match:
        secretKey: passwd.conf
        remoteRef:
          remoteKey: home/mosquitto-secret
