---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: nextcloud-secret-push
  namespace: productivity
spec:
  refreshInterval: 1h
  deletionPolicy: None
  secretStoreRefs:
    - name: openbao
      kind: ClusterSecretStore
  selector:
    secret:
      name: nextcloud-secret
  data:
    - match:
        secretKey: INIT_POSTGRES_DBNAME
        remoteRef:
          remoteKey: productivity/nextcloud-secret
    - match:
        secretKey: INIT_POSTGRES_HOST
        remoteRef:
          remoteKey: productivity/nextcloud-secret
    - match:
        secretKey: INIT_POSTGRES_USER
        remoteRef:
          remoteKey: productivity/nextcloud-secret
    - match:
        secretKey: INIT_POSTGRES_PASS
        remoteRef:
          remoteKey: productivity/nextcloud-secret
    - match:
        secretKey: INIT_POSTGRES_SUPER_PASS
        remoteRef:
          remoteKey: productivity/nextcloud-secret
    - match:
        secretKey: POSTGRES_HOST
        remoteRef:
          remoteKey: productivity/nextcloud-secret
    - match:
        secretKey: POSTGRES_DB
        remoteRef:
          remoteKey: productivity/nextcloud-secret
    - match:
        secretKey: POSTGRES_USER
        remoteRef:
          remoteKey: productivity/nextcloud-secret
    - match:
        secretKey: POSTGRES_PASSWORD
        remoteRef:
          remoteKey: productivity/nextcloud-secret
    - match:
        secretKey: NEXTCLOUD_ADMIN_USER
        remoteRef:
          remoteKey: productivity/nextcloud-secret
    - match:
        secretKey: NEXTCLOUD_ADMIN_PASSWORD
        remoteRef:
          remoteKey: productivity/nextcloud-secret
    - match:
        secretKey: OIDC_CLIENT_ID
        remoteRef:
          remoteKey: productivity/nextcloud-secret
    - match:
        secretKey: OIDC_CLIENT_SECRET
        remoteRef:
          remoteKey: productivity/nextcloud-secret
