---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: gitea-secret-push
  namespace: develop
spec:
  refreshInterval: 1h
  deletionPolicy: None
  secretStoreRefs:
    - name: openbao
      kind: ClusterSecretStore
  selector:
    secret:
      name: gitea-secret
  data:
    - match:
        secretKey: username
        remoteRef:
          remoteKey: develop/gitea-secret
    - match:
        secretKey: password
        remoteRef:
          remoteKey: develop/gitea-secret
    - match:
        secretKey: GITEA__database__USER
        remoteRef:
          remoteKey: develop/gitea-secret
    - match:
        secretKey: GITEA__database__PASSWD
        remoteRef:
          remoteKey: develop/gitea-secret
    - match:
        secretKey: GITEA__security__SECRET_KEY
        remoteRef:
          remoteKey: develop/gitea-secret
    - match:
        secretKey: GITEA__security__INTERNAL_TOKEN
        remoteRef:
          remoteKey: develop/gitea-secret
    - match:
        secretKey: GITEA__server__LFS_JWT_SECRET
        remoteRef:
          remoteKey: develop/gitea-secret
    - match:
        secretKey: GITEA__oauth2__JWT_SECRET
        remoteRef:
          remoteKey: develop/gitea-secret
    - match:
        secretKey: INIT_POSTGRES_HOST
        remoteRef:
          remoteKey: develop/gitea-secret
    - match:
        secretKey: INIT_POSTGRES_USER
        remoteRef:
          remoteKey: develop/gitea-secret
    - match:
        secretKey: INIT_POSTGRES_PASS
        remoteRef:
          remoteKey: develop/gitea-secret
    - match:
        secretKey: INIT_POSTGRES_DBNAME
        remoteRef:
          remoteKey: develop/gitea-secret
    - match:
        secretKey: INIT_POSTGRES_SUPER_PASS
        remoteRef:
          remoteKey: develop/gitea-secret
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: gitea-oauth-secret-push
  namespace: develop
spec:
  refreshInterval: 1h
  deletionPolicy: None
  secretStoreRefs:
    - name: openbao
      kind: ClusterSecretStore
  selector:
    secret:
      name: gitea-oauth-secret
  data:
    - match:
        secretKey: key
        remoteRef:
          remoteKey: develop/gitea-oauth-secret
    - match:
        secretKey: secret
        remoteRef:
          remoteKey: develop/gitea-oauth-secret
