---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: actions-runner-controller-auth-secret-push
  namespace: actions-runner-system
spec:
  refreshInterval: 1h
  deletionPolicy: None
  secretStoreRefs:
    - name: openbao
      kind: ClusterSecretStore
  selector:
    secret:
      name: actions-runner-controller-auth-secret
  data:
    - match:
        secretKey: ACTION_RUNNER_CONTROLLER_GITHUB_APP_ID
        remoteRef:
          remoteKey: actions-runner-system/actions-runner-controller-auth-secret
    - match:
        secretKey: ACTION_RUNNER_CONTROLLER_GITHUB_INSTALLATION_ID
        remoteRef:
          remoteKey: actions-runner-system/actions-runner-controller-auth-secret
    - match:
        secretKey: ACTION_RUNNER_CONTROLLER_GITHUB_PRIVATE_KEY
        remoteRef:
          remoteKey: actions-runner-system/actions-runner-controller-auth-secret
