---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/talos.dev/serviceaccount_v1alpha1.json
apiVersion: talos.dev/v1alpha1
kind: ServiceAccount
metadata:
  name: arc-flux-talos-talos-api
spec:
  # os:admin role allows full access to Talos API including image management
  roles:
    - os:admin
