---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: talos-s3-secret-push
  namespace: kube-system
spec:
  refreshInterval: 1h
  deletionPolicy: None
  secretStoreRefs:
    - name: openbao
      kind: ClusterSecretStore
  selector:
    secret:
      name: talos-s3-secret
  data:
    - match:
        secretKey: AWS_REGION
        remoteRef:
          remoteKey: kube-system/talos-s3-secret
    - match:
        secretKey: AWS_ACCESS_KEY_ID
        remoteRef:
          remoteKey: kube-system/talos-s3-secret
    - match:
        secretKey: AWS_SECRET_ACCESS_KEY
        remoteRef:
          remoteKey: kube-system/talos-s3-secret
    - match:
        secretKey: CUSTOM_S3_ENDPOINT
        remoteRef:
          remoteKey: kube-system/talos-s3-secret
    - match:
        secretKey: BUCKET
        remoteRef:
          remoteKey: kube-system/talos-s3-secret
    - match:
        secretKey: CLUSTER_NAME
        remoteRef:
          remoteKey: kube-system/talos-s3-secret
    - match:
        secretKey: S3_PREFIX
        remoteRef:
          remoteKey: kube-system/talos-s3-secret
    - match:
        secretKey: AGE_X25519_PUBLIC_KEY
        remoteRef:
          remoteKey: kube-system/talos-s3-secret
