---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: kopia-maintenance-r2-secret-push
  namespace: volsync-system
spec:
  refreshInterval: 1h
  deletionPolicy: None
  secretStoreRefs:
    - name: openbao
      kind: ClusterSecretStore
  selector:
    secret:
      name: kopia-maintenance-r2-secret
  data:
    - match:
        secretKey: KOPIA_REPOSITORY
        remoteRef:
          remoteKey: volsync-system/kopia-maintenance-r2-secret
    - match:
        secretKey: KOPIA_PASSWORD
        remoteRef:
          remoteKey: volsync-system/kopia-maintenance-r2-secret
    - match:
        secretKey: AWS_ACCESS_KEY_ID
        remoteRef:
          remoteKey: volsync-system/kopia-maintenance-r2-secret
    - match:
        secretKey: AWS_SECRET_ACCESS_KEY
        remoteRef:
          remoteKey: volsync-system/kopia-maintenance-r2-secret
    - match:
        secretKey: AWS_S3_ENDPOINT
        remoteRef:
          remoteKey: volsync-system/kopia-maintenance-r2-secret
