# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bw-seed-actions-runner-controller
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: bw-seed-actions-runner-controller
  dataFrom:
    - extract:
        key: actions-runner-controller
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bw-seed-alertmanager
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: bw-seed-alertmanager
  dataFrom:
    - extract:
        key: alertmanager
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bw-seed-atuin
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: bw-seed-atuin
  dataFrom:
    - extract:
        key: atuin
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bw-seed-audiobookshelf
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: bw-seed-audiobookshelf
  dataFrom:
    - extract:
        key: audiobookshelf
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bw-seed-authentik
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: bw-seed-authentik
  dataFrom:
    - extract:
        key: authentik
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bw-seed-autobrr
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: bw-seed-autobrr
  dataFrom:
    - extract:
        key: autobrr
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bw-seed-azure-ai
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: bw-seed-azure-ai
  dataFrom:
    - extract:
        key: azure-ai
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bw-seed-bazarr
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: bw-seed-bazarr
  dataFrom:
    - extract:
        key: bazarr
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bw-seed-calibre-web
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: bw-seed-calibre-web
  dataFrom:
    - extract:
        key: calibre-web
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bw-seed-cloudflare
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: bw-seed-cloudflare
  dataFrom:
    - extract:
        key: cloudflare
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bw-seed-cloudnative-pg
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: bw-seed-cloudnative-pg
  dataFrom:
    - extract:
        key: cloudnative-pg
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bw-seed-couchdb
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: bw-seed-couchdb
  dataFrom:
    - extract:
        key: couchdb
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bw-seed-cross-seed
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: bw-seed-cross-seed
  dataFrom:
    - extract:
        key: cross-seed
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bw-seed-drone
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: bw-seed-drone
  dataFrom:
    - extract:
        key: drone
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bw-seed-frigate
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: bw-seed-frigate
  dataFrom:
    - extract:
        key: frigate
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bw-seed-garage
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: bw-seed-garage
  dataFrom:
    - extract:
        key: garage
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bw-seed-gatus
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: bw-seed-gatus
  dataFrom:
    - extract:
        key: gatus
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bw-seed-gitea
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: bw-seed-gitea
  dataFrom:
    - extract:
        key: gitea
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bw-seed-grafana
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: bw-seed-grafana
  dataFrom:
    - extract:
        key: grafana
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bw-seed-grocy
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: bw-seed-grocy
  dataFrom:
    - extract:
        key: grocy
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bw-seed-homeassistant
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: bw-seed-homeassistant
  dataFrom:
    - extract:
        key: homeassistant
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bw-seed-homebox
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: bw-seed-homebox
  dataFrom:
    - extract:
        key: homebox
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bw-seed-homepage
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: bw-seed-homepage
  dataFrom:
    - extract:
        key: homepage
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bw-seed-immich
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: bw-seed-immich
  dataFrom:
    - extract:
        key: immich
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bw-seed-influxdb
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: bw-seed-influxdb
  dataFrom:
    - extract:
        key: influxdb
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bw-seed-jellyfin
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: bw-seed-jellyfin
  dataFrom:
    - extract:
        key: jellyfin
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bw-seed-jellyseerr
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: bw-seed-jellyseerr
  dataFrom:
    - extract:
        key: jellyseerr
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bw-seed-joplin
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: bw-seed-joplin
  dataFrom:
    - extract:
        key: joplin
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bw-seed-karakeep
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: bw-seed-karakeep
  dataFrom:
    - extract:
        key: karakeep
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bw-seed-kometa
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: bw-seed-kometa
  dataFrom:
    - extract:
        key: kometa
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bw-seed-lidarr
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: bw-seed-lidarr
  dataFrom:
    - extract:
        key: lidarr
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bw-seed-mealie
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: bw-seed-mealie
  dataFrom:
    - extract:
        key: mealie
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bw-seed-mosquitto
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: bw-seed-mosquitto
  dataFrom:
    - extract:
        key: mosquitto
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bw-seed-mullvad
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: bw-seed-mullvad
  dataFrom:
    - extract:
        key: mullvad
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bw-seed-n8n
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: bw-seed-n8n
  dataFrom:
    - extract:
        key: n8n
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bw-seed-nextcloud
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: bw-seed-nextcloud
  dataFrom:
    - extract:
        key: nextcloud
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bw-seed-nexus
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: bw-seed-nexus
  dataFrom:
    - extract:
        key: nexus
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bw-seed-nodered
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: bw-seed-nodered
  dataFrom:
    - extract:
        key: nodered
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bw-seed-notifiarr
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: bw-seed-notifiarr
  dataFrom:
    - extract:
        key: notifiarr
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bw-seed-plex
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: bw-seed-plex
  dataFrom:
    - extract:
        key: plex
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bw-seed-prowlarr
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: bw-seed-prowlarr
  dataFrom:
    - extract:
        key: prowlarr
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bw-seed-pushover
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: bw-seed-pushover
  dataFrom:
    - extract:
        key: pushover
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bw-seed-qbittorrent
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: bw-seed-qbittorrent
  dataFrom:
    - extract:
        key: qbittorrent
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bw-seed-r2
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: bw-seed-r2
  dataFrom:
    - extract:
        key: r2
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bw-seed-radarr
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: bw-seed-radarr
  dataFrom:
    - extract:
        key: radarr
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bw-seed-readarr-audiobooks
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: bw-seed-readarr-audiobooks
  dataFrom:
    - extract:
        key: readarr-audiobooks
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bw-seed-readarr-ebooks
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: bw-seed-readarr-ebooks
  dataFrom:
    - extract:
        key: readarr-ebooks
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bw-seed-rreading-glasses
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: bw-seed-rreading-glasses
  dataFrom:
    - extract:
        key: rreading-glasses
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bw-seed-sabnzbd
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: bw-seed-sabnzbd
  dataFrom:
    - extract:
        key: sabnzbd
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bw-seed-smtp-relay
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: bw-seed-smtp-relay
  dataFrom:
    - extract:
        key: smtp-relay
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bw-seed-sonarr
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: bw-seed-sonarr
  dataFrom:
    - extract:
        key: sonarr
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bw-seed-syncthing
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: bw-seed-syncthing
  dataFrom:
    - extract:
        key: syncthing
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bw-seed-tailscale-operator
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: bw-seed-tailscale-operator
  dataFrom:
    - extract:
        key: tailscale-operator
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bw-seed-tautulli
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: bw-seed-tautulli
  dataFrom:
    - extract:
        key: tautulli
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bw-seed-tdarr
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: bw-seed-tdarr
  dataFrom:
    - extract:
        key: tdarr
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bw-seed-unifi
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: bw-seed-unifi
  dataFrom:
    - extract:
        key: unifi
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bw-seed-valheim
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: bw-seed-valheim
  dataFrom:
    - extract:
        key: valheim
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bw-seed-volsync-local-template
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: bw-seed-volsync-local-template
  dataFrom:
    - extract:
        key: volsync-local-template
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bw-seed-volsync-r2-template
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  target:
    name: bw-seed-volsync-r2-template
  dataFrom:
    - extract:
        key: volsync-r2-template
