---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: drone-secret-push
  namespace: develop
spec:
  refreshInterval: 1h
  deletionPolicy: None
  secretStoreRefs:
    - name: openbao
      kind: ClusterSecretStore
  selector:
    secret:
      name: drone-secret
  data:
    - match:
        secretKey: DRONE_GITEA_CLIENT_ID
        remoteRef:
          remoteKey: develop/drone-secret
    - match:
        secretKey: DRONE_GITEA_CLIENT_SECRET
        remoteRef:
          remoteKey: develop/drone-secret
    - match:
        secretKey: DRONE_RPC_SECRET
        remoteRef:
          remoteKey: develop/drone-secret
    - match:
        secretKey: DRONE_DATABASE_DATASOURCE
        remoteRef:
          remoteKey: develop/drone-secret
    - match:
        secretKey: INIT_POSTGRES_HOST
        remoteRef:
          remoteKey: develop/drone-secret
    - match:
        secretKey: INIT_POSTGRES_USER
        remoteRef:
          remoteKey: develop/drone-secret
    - match:
        secretKey: INIT_POSTGRES_PASS
        remoteRef:
          remoteKey: develop/drone-secret
    - match:
        secretKey: INIT_POSTGRES_DBNAME
        remoteRef:
          remoteKey: develop/drone-secret
    - match:
        secretKey: INIT_POSTGRES_SUPER_PASS
        remoteRef:
          remoteKey: develop/drone-secret
