---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: plex-secret-push
  namespace: media
spec:
  refreshInterval: 1h
  deletionPolicy: None
  secretStoreRefs:
    - name: openbao
      kind: ClusterSecretStore
  selector:
    secret:
      name: plex-secret
  data:
    - match:
        secretKey: PLEX_TOKEN
        remoteRef:
          remoteKey: media/plex-secret
