---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: unpackerr-secret-push
  namespace: download
spec:
  refreshInterval: 1h
  deletionPolicy: None
  secretStoreRefs:
    - name: openbao
      kind: ClusterSecretStore
  selector:
    secret:
      name: unpackerr-secret
  data:
    - match:
        secretKey: UN_SONARR_0_URL
        remoteRef:
          remoteKey: download/unpackerr-secret
    - match:
        secretKey: UN_SONARR_0_API_KEY
        remoteRef:
          remoteKey: download/unpackerr-secret
    - match:
        secretKey: UN_SONARR_0_PATHS_0
        remoteRef:
          remoteKey: download/unpackerr-secret
    - match:
        secretKey: UN_SONARR_0_PROTOCOLS
        remoteRef:
          remoteKey: download/unpackerr-secret
    - match:
        secretKey: UN_SONARR_0_TIMEOUT
        remoteRef:
          remoteKey: download/unpackerr-secret
    - match:
        secretKey: UN_SONARR_0_DELETE_DELAY
        remoteRef:
          remoteKey: download/unpackerr-secret
    - match:
        secretKey: UN_SONARR_0_DELETE_ORIG
        remoteRef:
          remoteKey: download/unpackerr-secret
    - match:
        secretKey: UN_RADARR_0_URL
        remoteRef:
          remoteKey: download/unpackerr-secret
    - match:
        secretKey: UN_RADARR_0_API_KEY
        remoteRef:
          remoteKey: download/unpackerr-secret
    - match:
        secretKey: UN_RADARR_0_PATHS_0
        remoteRef:
          remoteKey: download/unpackerr-secret
    - match:
        secretKey: UN_RADARR_0_PROTOCOLS
        remoteRef:
          remoteKey: download/unpackerr-secret
    - match:
        secretKey: UN_RADARR_0_TIMEOUT
        remoteRef:
          remoteKey: download/unpackerr-secret
    - match:
        secretKey: UN_RADARR_0_DELETE_DELAY
        remoteRef:
          remoteKey: download/unpackerr-secret
    - match:
        secretKey: UN_RADARR_0_DELETE_ORIG
        remoteRef:
          remoteKey: download/unpackerr-secret
    - match:
        secretKey: UN_LIDARR_0_URL
        remoteRef:
          remoteKey: download/unpackerr-secret
    - match:
        secretKey: UN_LIDARR_0_API_KEY
        remoteRef:
          remoteKey: download/unpackerr-secret
    - match:
        secretKey: UN_LIDARR_0_PATHS_0
        remoteRef:
          remoteKey: download/unpackerr-secret
    - match:
        secretKey: UN_LIDARR_0_PROTOCOLS
        remoteRef:
          remoteKey: download/unpackerr-secret
    - match:
        secretKey: UN_LIDARR_0_TIMEOUT
        remoteRef:
          remoteKey: download/unpackerr-secret
    - match:
        secretKey: UN_LIDARR_0_DELETE_DELAY
        remoteRef:
          remoteKey: download/unpackerr-secret
    - match:
        secretKey: UN_LIDARR_0_DELETE_ORIG
        remoteRef:
          remoteKey: download/unpackerr-secret
    - match:
        secretKey: UN_READARR_0_URL
        remoteRef:
          remoteKey: download/unpackerr-secret
    - match:
        secretKey: UN_READARR_0_API_KEY
        remoteRef:
          remoteKey: download/unpackerr-secret
    - match:
        secretKey: UN_READARR_0_PATHS_0
        remoteRef:
          remoteKey: download/unpackerr-secret
    - match:
        secretKey: UN_READARR_0_PROTOCOLS
        remoteRef:
          remoteKey: download/unpackerr-secret
    - match:
        secretKey: UN_READARR_0_TIMEOUT
        remoteRef:
          remoteKey: download/unpackerr-secret
    - match:
        secretKey: UN_READARR_0_DELETE_DELAY
        remoteRef:
          remoteKey: download/unpackerr-secret
    - match:
        secretKey: UN_READARR_0_DELETE_ORIG
        remoteRef:
          remoteKey: download/unpackerr-secret
    - match:
        secretKey: UN_READARR_1_URL
        remoteRef:
          remoteKey: download/unpackerr-secret
    - match:
        secretKey: UN_READARR_1_API_KEY
        remoteRef:
          remoteKey: download/unpackerr-secret
    - match:
        secretKey: UN_READARR_1_PATHS_0
        remoteRef:
          remoteKey: download/unpackerr-secret
    - match:
        secretKey: UN_READARR_1_PROTOCOLS
        remoteRef:
          remoteKey: download/unpackerr-secret
    - match:
        secretKey: UN_READARR_1_TIMEOUT
        remoteRef:
          remoteKey: download/unpackerr-secret
    - match:
        secretKey: UN_READARR_1_DELETE_DELAY
        remoteRef:
          remoteKey: download/unpackerr-secret
    - match:
        secretKey: UN_READARR_1_DELETE_ORIG
        remoteRef:
          remoteKey: download/unpackerr-secret
