---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: external-dns-secret-unifi-push
  namespace: network
spec:
  refreshInterval: 1h
  deletionPolicy: None
  secretStoreRefs:
    - name: openbao
      kind: ClusterSecretStore
  selector:
    secret:
      name: external-dns-secret-unifi
  data:
    - match:
        secretKey: EXTERNAL_DNS_UNIFI_USER
        remoteRef:
          remoteKey: network/external-dns-secret-unifi
    - match:
        secretKey: EXTERNAL_DNS_UNIFI_PASS
        remoteRef:
          remoteKey: network/external-dns-secret-unifi
