---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: cloudnative-pg-secret-push
  namespace: database
spec:
  refreshInterval: 1h
  deletionPolicy: None
  secretStoreRefs:
    - name: openbao
      kind: ClusterSecretStore
  selector:
    secret:
      name: cloudnative-pg-secret
  data:
    - match:
        secretKey: username
        remoteRef:
          remoteKey: database/cloudnative-pg-secret
    - match:
        secretKey: password
        remoteRef:
          remoteKey: database/cloudnative-pg-secret
    - match:
        secretKey: s3-access-key-id
        remoteRef:
          remoteKey: database/cloudnative-pg-secret
    - match:
        secretKey: s3-secret-access-key
        remoteRef:
          remoteKey: database/cloudnative-pg-secret
    - match:
        secretKey: s3-access-key-id-garage
        remoteRef:
          remoteKey: database/cloudnative-pg-secret
    - match:
        secretKey: s3-secret-access-key-garage
        remoteRef:
          remoteKey: database/cloudnative-pg-secret
