---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: node-red-secret-push
  namespace: productivity
spec:
  refreshInterval: 1h
  deletionPolicy: None
  secretStoreRefs:
    - name: openbao
      kind: ClusterSecretStore
  selector:
    secret:
      name: node-red-secret
  data:
    - match:
        secretKey: NODE_RED_CREDENTIAL_SECRET
        remoteRef:
          remoteKey: productivity/node-red-secret
    - match:
        secretKey: OPENAI_API_KEY
        remoteRef:
          remoteKey: productivity/node-red-secret
    - match:
        secretKey: OPENAI_BASE_URL
        remoteRef:
          remoteKey: productivity/node-red-secret
