---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/core/service_v1.json
apiVersion: v1
kind: Service
metadata:
  name: ops-console
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ops-console
  ports:
    - name: http
      port: 8000
      targetPort: http
