---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: homebox-secret-push
  namespace: productivity
spec:
  refreshInterval: 1h
  deletionPolicy: None
  secretStoreRefs:
    - name: openbao
      kind: ClusterSecretStore
  selector:
    secret:
      name: homebox-secret
  data:
    - match:
        secretKey: INIT_POSTGRES_DBNAME
        remoteRef:
          remoteKey: productivity/homebox-secret
    - match:
        secretKey: INIT_POSTGRES_HOST
        remoteRef:
          remoteKey: productivity/homebox-secret
    - match:
        secretKey: INIT_POSTGRES_USER
        remoteRef:
          remoteKey: productivity/homebox-secret
    - match:
        secretKey: INIT_POSTGRES_PASS
        remoteRef:
          remoteKey: productivity/homebox-secret
    - match:
        secretKey: INIT_POSTGRES_SUPER_PASS
        remoteRef:
          remoteKey: productivity/homebox-secret
    - match:
        secretKey: HBOX_DATABASE_HOST
        remoteRef:
          remoteKey: productivity/homebox-secret
    - match:
        secretKey: HBOX_DATABASE_PORT
        remoteRef:
          remoteKey: productivity/homebox-secret
    - match:
        secretKey: HBOX_DATABASE_USERNAME
        remoteRef:
          remoteKey: productivity/homebox-secret
    - match:
        secretKey: HBOX_DATABASE_PASSWORD
        remoteRef:
          remoteKey: productivity/homebox-secret
    - match:
        secretKey: HBOX_DATABASE_DATABASE
        remoteRef:
          remoteKey: productivity/homebox-secret
    - match:
        secretKey: HBOX_OIDC_CLIENT_ID
        remoteRef:
          remoteKey: productivity/homebox-secret
    - match:
        secretKey: HBOX_OIDC_CLIENT_SECRET
        remoteRef:
          remoteKey: productivity/homebox-secret
