---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: operator-oauth-push
  namespace: network
spec:
  refreshInterval: 1h
  deletionPolicy: None
  secretStoreRefs:
    - name: openbao
      kind: ClusterSecretStore
  selector:
    secret:
      name: operator-oauth
  data:
    - match:
        secretKey: client_id
        remoteRef:
          remoteKey: network/operator-oauth
    - match:
        secretKey: client_secret
        remoteRef:
          remoteKey: network/operator-oauth
