---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: influxdb-secret-push
  namespace: database
spec:
  refreshInterval: 1h
  deletionPolicy: None
  secretStoreRefs:
    - name: openbao
      kind: ClusterSecretStore
  selector:
    secret:
      name: influxdb-secret
  data:
    - match:
        secretKey: DOCKER_INFLUXDB_INIT_USERNAME
        remoteRef:
          remoteKey: database/influxdb-secret
    - match:
        secretKey: DOCKER_INFLUXDB_INIT_PASSWORD
        remoteRef:
          remoteKey: database/influxdb-secret
    - match:
        secretKey: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
        remoteRef:
          remoteKey: database/influxdb-secret
    - match:
        secretKey: DOCKER_INFLUXDB_INIT_ORG
        remoteRef:
          remoteKey: database/influxdb-secret
    - match:
        secretKey: DOCKER_INFLUXDB_INIT_BUCKET
        remoteRef:
          remoteKey: database/influxdb-secret
