---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: lidarr-secret-push
  namespace: media
spec:
  refreshInterval: 1h
  deletionPolicy: None
  secretStoreRefs:
    - name: openbao
      kind: ClusterSecretStore
  selector:
    secret:
      name: lidarr-secret
  data:
    - match:
        secretKey: LIDARR__AUTH__APIKEY
        remoteRef:
          remoteKey: media/lidarr-secret
    - match:
        secretKey: LIDARR__POSTGRES__HOST
        remoteRef:
          remoteKey: media/lidarr-secret
    - match:
        secretKey: LIDARR__POSTGRES__PORT
        remoteRef:
          remoteKey: media/lidarr-secret
    - match:
        secretKey: LIDARR__POSTGRES__USER
        remoteRef:
          remoteKey: media/lidarr-secret
    - match:
        secretKey: LIDARR__POSTGRES__PASSWORD
        remoteRef:
          remoteKey: media/lidarr-secret
    - match:
        secretKey: LIDARR__POSTGRES__MAINDB
        remoteRef:
          remoteKey: media/lidarr-secret
    - match:
        secretKey: LIDARR__POSTGRES__LOGDB
        remoteRef:
          remoteKey: media/lidarr-secret
    - match:
        secretKey: INIT_POSTGRES_HOST
        remoteRef:
          remoteKey: media/lidarr-secret
    - match:
        secretKey: INIT_POSTGRES_USER
        remoteRef:
          remoteKey: media/lidarr-secret
    - match:
        secretKey: INIT_POSTGRES_PASS
        remoteRef:
          remoteKey: media/lidarr-secret
    - match:
        secretKey: INIT_POSTGRES_DBNAME
        remoteRef:
          remoteKey: media/lidarr-secret
    - match:
        secretKey: INIT_POSTGRES_SUPER_PASS
        remoteRef:
          remoteKey: media/lidarr-secret
