---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: smtp-relay-push
  namespace: infrastructure
spec:
  refreshInterval: 1h
  deletionPolicy: None
  secretStoreRefs:
    - name: openbao
      kind: ClusterSecretStore
  selector:
    secret:
      name: smtp-relay
  data:
    - match:
        secretKey: SMTP_RELAY_HOSTNAME
        remoteRef:
          remoteKey: infrastructure/smtp-relay
    - match:
        secretKey: SMTP_RELAY_SERVER
        remoteRef:
          remoteKey: infrastructure/smtp-relay
    - match:
        secretKey: SMTP_RELAY_USERNAME
        remoteRef:
          remoteKey: infrastructure/smtp-relay
    - match:
        secretKey: SMTP_RELAY_PASSWORD
        remoteRef:
          remoteKey: infrastructure/smtp-relay
